//Gastos
export const CREAR_PRODUCTO = 'CREAR_PRODUCTO';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTOS';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTOS';
export const TACHAR_PRODUCTO = 'TACHAR_PRODUCTOS';

